version: "3"

services:
  api:
    build: ./api-server
    env_file:
    - .env
    depends_on:
      - dbsvc
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_SVC_URL=http://dbsvc:8090
    ports:
      - "8080:8080"
    networks:
      - pet-project_default
  dbsvc:
    build: ./db-server
    env_file:
    - .env
    ports:
      - "8090:8090"
    environment:
      - PG_DSN=${PG_DSN}
    networks:
      - pet-project_default
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pet-project_default
networks:
  pet-project_default:
    driver: bridge
volumes:
  redis_data:
