version: "3"

services:
  api:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile.api
    env_file:
    - ../configs/.env
    depends_on:
      - dbsvc
    environment:
      - DB_SVC_URL=http://dbsvc:8090
    ports:
      - "8080:8080"
    networks:
      - pet-project_default
  dbsvc:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.db
    env_file:
    - ../configs/.env
    networks:
      - pet-project_default
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pet-project_default
networks:
  pet-project_default:
    driver: bridge
volumes:
  redis_data:
