version: "3"

services:
  api:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile.api
    env_file:
    - ../configs/.env
    depends_on:
      - dbsvc
    environment:
      - DB_SVC_URL=http://dbsvc:8090
    ports:
      - "8080:8080"
    networks:
      - pet-project_default
  dbsvc:
    build:
      context: ../
      dockerfile: deploy/Dockerfile.db
    depends_on:
      - postgres
    env_file:
    - ../configs/.env
    networks:
      - pet-project_default
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - pet-project_default
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pet-project_default
networks:
  pet-project_default:
    driver: bridge
volumes:
  redis_data:
  pg_data:
